server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/maindata?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true
    username: root
    password: root
  thymeleaf:
    cache: false
  redis:
    enabled: true
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1  # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-idle: 8
        min-idle: 0
